meta_title: "Find The Prompt"
meta_og_title: "Find The Prompt"
meta_description: "Find the AI prompt used to generate an image as quickly as possible. Everyday a new prompt to discover!"
meta_og_description: "Find the AI prompt used to generate an image as quickly as possible. Everyday a new prompt to discover!"
meta_og_type: "website"
meta_image: "findtheprompt-cover.png" # Une image dans votre dossier app/assets/images/
